import accordionImage from "@public/images/accordion-image.png";
import music1 from "@public/music/music1.mp3";
import music2 from "@public/music/music2.mp3";
import music3 from "@public/music/music3.mp3";
import music4 from "@public/music/music4.mp3";
export const SongsList = [
  {
    author: "Aisha Abdi",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Neighboorhood Gunfire",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music1,
  },
  {
    author: "Karim Mansour",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Close-range Gunfire",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music2,
  },
  {
    author: "Layla Assad",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Outlying Gunshots",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music3,
  },
  {
    author: "Ahmed Al-Rawi",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Explosion Impact",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music4,
  },
  {
    author: "Jamal Kassab",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Consecutive Blasts",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music1,
  },
  {
    author: "Jamal Kassab",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Consecutive Blasts",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music2,
  },
  {
    author: "Noura Al-Hakim",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Falling Rubble",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music3,
  },
  {
    author: "Khaled Mansoor",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Urban Detonation",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music4,
  },
  {
    author: "Rafiq Matar",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Moving Tank",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music1,
  },
  {
    author: "Fatima Khalil",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Aiming Tank",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music2,
  },
  {
    author: "Omar Al-Maliki",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Tank Convoy",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music3,
  },
  {
    author: "Yasmeen Al-Khafaji",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Hovering Helicopter",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music4,
  },
  {
    author: "Noor Al-Haddad",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Patrolling Drone",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music1,
  },
  {
    author: "Farida Azimi",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Helicopter Surveillance",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music2,
  },
  {
    author: "Rami Hasan",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Ambulance Siren",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music3,
  },
  {
    author: "Mulu Gebre",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Bones Cracking",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music4,
  },
  {
    author: "Saeed Al-Farsi",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Falling Bomb",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music2,
  },
  {
    author: "Nadia Hariri",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Courtyard Gunfight",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music3,
  },
  {
    author: "Adil Al-Qahtani",
    authorDetails:
      "Loud airstrikes just happened out of nowhere in Idlib. Now, when people celebrate with fireworks somewhere else, it brings back scary feelings of fear and loss for me.",
    songTitle: "Drone Mission",
    coverImage: accordionImage,
    loopedAudio: "Yes",
    simpleRate: "16-Bit Stereo, 44.1kHz",
    audioFilesIncluded: "MP3, WAV",
    bitRate: "320 Kbps",
    mainTrackLength: "01:34",
    temoBPM: "85",
    downloadLink: "",
    songURL: music4,
  },
];
